-- Lab warehouse objects for FACT_OCP_COST_BY_PROJECT (gvenzl Oracle Free 23).
-- Runs as SYS during container first boot; APP_USER=costmgmt already exists.
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE costmgmt.fact_ocp_cost_by_project (
    usage_date          DATE NOT NULL,
    source_type         VARCHAR2(32) NOT NULL,
    cluster_id          VARCHAR2(256) NOT NULL,
    project             VARCHAR2(256) NOT NULL,
    currency            VARCHAR2(16) NOT NULL,
    cost_total          NUMBER(38, 10) NOT NULL,
    cost_raw            NUMBER(38, 10) NOT NULL,
    cost_markup         NUMBER(38, 10) NOT NULL,
    cost_usage          NUMBER(38, 10) NOT NULL,
    infra_total         NUMBER(38, 10) NOT NULL,
    supplementary_total NUMBER(38, 10) NOT NULL,
    extracted_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    etl_run_id          NUMBER NOT NULL,
    CONSTRAINT uq_fact_ocp_cost_by_project UNIQUE (usage_date, source_type, cluster_id, project, currency)
);

CREATE TABLE costmgmt.etl_watermark (
    job_name            VARCHAR2(64) NOT NULL,
    last_success_end    DATE NOT NULL,
    last_success_run_id NUMBER,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_etl_watermark PRIMARY KEY (job_name)
);

CREATE TABLE costmgmt.etl_run (
    etl_run_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_name       VARCHAR2(64) NOT NULL,
    window_start   DATE,
    window_end     DATE,
    status         VARCHAR2(32) NOT NULL,
    rows_in        NUMBER,
    rows_upserted  NUMBER,
    api_pages      NUMBER,
    error_message  VARCHAR2(4000),
    started_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_etl_run PRIMARY KEY (etl_run_id)
);
